name: Humilis Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11093
title: The Photo Experiment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13120d'
    - '#babca4'
    - '#4d3a1a'
    - '#7a7b5b'
    - '#f6f0c1'
  brandStrength: 0.1875
  lightness: 0.06534762657247484
  saturation: 0.10205104714259505
  rhythmicContrast: 0.7921532529871911
purpose: []
